Revise "word2vec-pretraining_vn" - Phần 1
aivivn/d2l-vn pull request #2617
Opened 2020-08-30 09:07 UTC by cuongvng

close #2604

2020-09-03 13:23 UTC, lkhphuc requested changes
còn 2 chỗ bị sai.

2020-09-03 13:23 UTC, lkhphuc commented on chapter_natural-language-processing-pretraining/word2vec-pretraining_vn.md
> +Khi ta nhập vào chỉ số $i$ của một từ, tầng embedding sẽ trả về vector từ tương ứng là cột thứ $i$ của ma trận trọng số.
```suggestion
Khi ta nhập vào chỉ số $i$ của một từ, tầng embedding sẽ trả về vector từ tương ứng là hàng thứ $i$ của ma trận trọng số.
```

2020-09-03 13:23 UTC, lkhphuc commented on chapter_natural-language-processing-pretraining/word2vec-pretraining_vn.md
> +Đầu ra của toán tử nhân minibatch trên hai batch đầu vào là $n$ ma trận $\mathbf{X}_1\mathbf{Y}_1, \ldots, \mathbf{X}_n\mathbf{Y}_n$ có kích thước là $a\times c$.
ơ cái này câu gốc mới đúng chứ nhỉ?
```suggestion
Đầu ra của toán tử nhân ma trận trên hai batch đầu vào là $n$ ma trận $\mathbf{X}_1\mathbf{Y}_1, \ldots, \mathbf{X}_n\mathbf{Y}_n$ có kích thước là $a\times c$.   
```

2020-09-03 13:23 UTC, lkhphuc commented on chapter_natural-language-processing-pretraining/word2vec-pretraining_vn.md
> +và chỉ số `contexts_and_negatives` của từ ngữ cảnh và từ nhiễu được ghép nối.
```suggestion
và chỉ số `contexts_and_negatives` được nối lại từ chỉ số của từ ngữ cảnh và từ nhiễu.
```

2020-09-03 14:19 UTC, cuongvng commented on chapter_natural-language-processing-pretraining/word2vec-pretraining_vn.md
> +Đầu ra của toán tử nhân minibatch trên hai batch đầu vào là $n$ ma trận $\mathbf{X}_1\mathbf{Y}_1, \ldots, \mathbf{X}_n\mathbf{Y}_n$ có kích thước là $a\times c$.
em thấy đoạn này đang nói đến `Minibatch Multiplication` mà?

2020-09-04 09:50 UTC, lkhphuc approved these changes

2020-09-04 10:34 UTC, duythanhvn approved these changes

2020-09-04 10:36 UTC, merged