Dịch "gan_vn" - Phần 2
aivivn/d2l-vn pull request #2743
Opened 2020-09-08 04:55 UTC by lyphilong

## Pull Request Checklist

**Đánh dấu tick (sau khi "Create Pull Request") vào các mục dưới đây:**

* [ ] Pull Request này tương ứng với issue nào? Điền số issue sau dấu `#` (không có dấu cách): Close #2726

* [ ] Bản dịch này có bám sát **[Bảng thuật ngữ](https://github.com/aivivn/d2l-vn/blob/master/glossary.md)** không? Nếu một từ/cụm chưa có trong Bảng thuật ngữ, hãy thảo luận thêm ở thẻ Discussions của dự án.

* [ ] Format của bản gốc có được giữ nguyên không?
     
* [ ] Trong một đoạn văn, mỗi câu văn đã được viết trong một dòng, giữa các dòng không có dòng trắng. Markdown sẽ coi những dòng liền nhau không có dòng trắng là một đoạn văn. Việc này giúp công đoạn review được thuận tiện hơn. Bạn đã kiểm tra rằng mỗi đoạn văn đã nằm một dòng?

* [ ] Điền tên đầy đủ của bạn vào mục **Những người thực hiện** ở cuối tập tin.

## Lưu ý cho người phản biện (Reviewer)

1. Chỉ review khi Pull Request (PR) này đã sẵn sàng cho việc review. Một PR sẵn sàng khi PR đó không có label `status: wip`.
2. Đã đọc kỹ hướng dẫn đóng góp và xem qua **[Bảng thuật ngữ](https://github.com/aivivn/d2l-vn/blob/master/glossary.md)**.

2020-09-13 13:52 UTC, rootonchair approved these changes
Thanks. LGTM

2020-09-13 13:52 UTC, rootonchair commented on chapter_generative-adversarial-networks/gan_vn.md
> +Cùng lúc đó, mạng phân biệt sẽ thích nghi với dữ liệu giả vừa mới tạo ra.
```suggestion
Đồng thời, mạng phân biệt sẽ thích nghi với dữ liệu giả vừa mới tạo ra.
```

2020-09-13 13:52 UTC, rootonchair commented on chapter_generative-adversarial-networks/gan_vn.md
> +Mạng phân biệt là một bộ phân loại nhị phân nhằm phân biệt xem đầu vào $x$ là thật (từ dữ liệu thật) hoặc giả (từ mạnh sinh).
```suggestion
Mạng phân biệt là một bộ phân loại nhị phân nhằm phân biệt xem đầu vào $x$ là thật (từ dữ liệu thật) hoặc giả (từ mạng sinh).
```

2020-09-13 13:52 UTC, rootonchair commented on chapter_generative-adversarial-networks/gan_vn.md
> +Thông thường, đầu ra của mạng phân biệt là một số dự đoán vô hướng $o\in\mathbb R$ cho đầu vào $\mathbf x$, chằng hạn như sử sụng một tầng kết nối đầy đủ với kích thước ẩn 1 và sau đó sẽ được đưa qua
```suggestion
Thông thường, đầu ra của mạng phân biệt là một số vô hướng $o\in\mathbb R$ dự đoán cho đầu vào $\mathbf x$, chằng hạn như sử sụng một tầng kết nối đầy đủ với kích thước ẩn 1 và sau đó sẽ được đưa qua hàm sigmoid để nhận được xác suất dự đoán $D(\mathbf x) = 1/(1+e^{-o})$.
```

2020-09-14 08:30 UTC, lyphilong commented
Thanks @rootonchair nhiều nha

2020-09-14 10:20 UTC, duythanhvn requested changes
Điền tên vào đi em nha.

2020-09-14 13:17 UTC, lkhphuc approved these changes

2020-09-14 13:17 UTC, lkhphuc commented on chapter_generative-adversarial-networks/gan_vn.md
> +Thông tin này, sẽ được dùng để cải thiện mạng sinh, v.v.
```suggestion
Thông tin này từ đó sẽ được dùng để cải thiện mạng sinh, và cứ tiếp tục như vậy.
```

2020-09-14 13:17 UTC, lkhphuc commented on chapter_generative-adversarial-networks/gan_vn.md
> +Cả hai mạng như trong cuộc cạnh tranh với nhau.
```suggestion
Cả hai mạng này sẽ cạnh tranh với nhau.
```

2020-09-15 04:22 UTC, duythanhvn approved these changes

2020-09-15 04:23 UTC, merged