Dịch "selecting-servers-gpus_vn" - Phần 1
aivivn/d2l-vn pull request #3024
Opened 2020-10-09 09:59 UTC by LongNguyen1984

Dịch lần 1

## Pull Request Checklist

**Đánh dấu tick (sau khi "Create Pull Request") vào các mục dưới đây:**

* [ ] Pull Request này tương ứng với issue nào? Điền số issue sau dấu `#` (không có dấu cách): Close #3001

* [ ] Bản dịch này có bám sát **[Bảng thuật ngữ](https://github.com/aivivn/d2l-vn/blob/master/glossary.md)** không? Nếu một từ/cụm chưa có trong Bảng thuật ngữ, hãy thảo luận thêm ở thẻ Discussions của dự án.

* [ ] Format của bản gốc có được giữ nguyên không?
     
* [ ] Trong một đoạn văn, mỗi câu văn đã được viết trong một dòng, giữa các dòng không có dòng trắng. Markdown sẽ coi những dòng liền nhau không có dòng trắng là một đoạn văn. Việc này giúp công đoạn review được thuận tiện hơn. Bạn đã kiểm tra rằng mỗi đoạn văn đã nằm một dòng?

* [ ] Điền tên đầy đủ của bạn vào mục **Những người thực hiện** ở cuối tập tin.

## Lưu ý cho người phản biện (Reviewer)

1. Chỉ review khi Pull Request (PR) này đã sẵn sàng cho việc review. Một PR sẵn sàng khi PR đó không có label `status: wip`.
2. Đã đọc kỹ hướng dẫn đóng góp và xem qua **[Bảng thuật ngữ](https://github.com/aivivn/d2l-vn/blob/master/glossary.md)**.

2020-10-14 03:23 UTC, cuongvng requested changes
Thank anh, thiếu 1 đoạn chưa dịch thôi.

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +Ở thời điểm hiện tại, GPU là công cụ tăng tốc phần cứng chi phí hiệu quả nhất cho việc học sâu.
```suggestion
Ở thời điểm hiện tại, GPU là công cụ tăng tốc phần cứng có hiệu quả về chi phí nhất cho việc học sâu.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +Hơn nữa, một máy chủ đơn có thể hỗ trợ đa GPU, tới 8 bộ cho các máy chủ cao cấp.
```suggestion
Hơn nữa, một máy chủ đơn có thể hỗ trợ đa GPU, tới 8 GPU với các máy chủ cao cấp.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +Số GPU điển hình hơn là đến 4 cho một máy trạm kỹ thuật,
```suggestion
Số GPU điển hình hơn là 4 cho một máy trạm kỹ thuật,
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +vì vấn đề đòi hỏi về tỏa nhiệt, làm mát và lượng điện tiêu thụ tăng vọt nhanh chóng vượt quá khả năng của một tòa nhà văn phòng có thể cung cấp.
```suggestion
vì vấn đề tỏa nhiệt, làm mát và lượng điện tiêu thụ sẽ tăng vọt  vượt quá khả năng một tòa nhà văn phòng có thể cung cấp.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +và các bản mẫu [G4](https://aws.amazon.com/blogs/aws/in-the-works-ec2-instances-g4-with-nvidia-t4-gpus/) là một giải pháp thực tế hơn nhiều.
```suggestion
Để triển khai trên số lượng lớn hơn, điện toán đám mây, chẳng hạn như các máy ảo [P3](https://aws.amazon.com/ec2/instance-types/p3/) và [G4](https://aws.amazon.com/blogs/aws/in-the-works-ec2-instances-g4-with-nvidia-t4-gpus/) của Amazon là một giải pháp thực tế hơn nhiều.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
Đoạn phía dưới chưa dịch anh.

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +vì mã hiệu quả cho việc triển khai có thể sử dụng nhiều năng lượng).
```suggestion
vì mã nguồn hiệu quả có thể ngốn nhiều năng lượng).
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +1. **Kích thước khung**. GPU có kích thước lớn và các đầu nối nguồn phụ trợ thường cần thêm không gian.
```suggestion
2. **Kích thước khung chứa**. GPU có kích thước lớn và các đầu nối nguồn phụ trợ thường cần thêm không gian.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +1. **Làm mát GPU**. Nếu bạn có số lượng lớn GPU, bạn có thể muốn đầu tư vào tản nhiệt nước.
```suggestion
3. **Làm mát GPU**. Nếu bạn có số lượng lớn GPU, bạn có thể muốn đầu tư vào tản nhiệt nước.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +Ngoài ra, với mục tiêu làm *thiết kế tham khảo* ngay cả khi chúng có số quạt làm mát ít hơn, vì chúng đủ mỏng để cho phép hút gió giữa các thiết bị.
```suggestion
Ngoài ra, có thể sử dụng các *thiết kế tham khảo* ngay cả khi chúng có số quạt làm mát ít hơn, vì chúng đủ mỏng để cho phép thông gió giữa các thiết bị.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +Nếu bạn mua một GPU có nhiều quạt, nó có thể quá dày để nhận đủ không khí khi lắp đặt nhiều GPU và bạn sẽ gặp phải tình trạng điều tiết nhiệt.
```suggestion
Nếu bạn mua một GPU có nhiều quạt, nó có thể quá dày để nhận đủ không khí khi lắp đặt nhiều GPU và bạn sẽ gặp phải tình trạng khó tản nhiệt.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +1. **Khe cắm PCIe**. Việc dịich chuyển dữ liệu đến và đi từ GPU (và trao đổi giữa các GPU) đòi hỏi nhiều băng thông.
```suggestion
4. **Khe cắm PCIe**. Việc dịich chuyển dữ liệu đến và đi từ GPU (và trao đổi giữa các GPU) đòi hỏi nhiều băng thông.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +băng thông 16x đó vẫn khả dụng khi nhiều GPU được sử dụng cùng lúc và nó có nghĩa là bạn đang nhận được tốc độ PCIe 3.0 thay vì PCIe 2.0 cho các khe cắm bổ sung.
```suggestion
băng thông 16x đó vẫn khả dụng khi nhiều GPU được sử dụng cùng lúc và tốc độ PCIe là 3.0 thay vì PCIe cho các khe cắm bổ sung.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +Mua GPU có thiết kế chuẩn hẹp và cho không khí đi giữa các GPU.
```suggestion
Mua GPU có thiết kế sẵn, hẹp và cho không khí đi giữa các GPU.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +Khuyến nghị sử dụng 128 GB DRAM. Mua một ổ SSD (1-2 TB NVMe) để lưu trữ cục bộ và một số ổ cứng để cấu hình RAID cho lưu trữ dữ liệu của bạn.
```suggestion
Khuyến nghị sử dụng 128 GB DRAM. Mua một ổ SSD (1-2 TB NVMe) để lưu trữ cục bộ và một số ổ cứng theo cấu hình RAID để lưu trữ dữ liệu của bạn.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +và bạn sẽ cần kiểm tra liệu máy chủ có hỗ trợ *yếu tố hình dạng vật lý* cho GPU hay không.
```suggestion
và bạn sẽ cần kiểm tra liệu máy chủ có hỗ trợ *yếu tố vật lý* cho GPU hay không.
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +Luồng không khí và bố trí đi dây có sự khác biệt đáng kể giữa GPU tiêu dùng và GPU máy chủ  (cụ thể ở đây là RTX 2080 so với Tesla V100).
```suggestion
Luồng không khí và bố trí đi dây có sự khác biệt đáng kể giữa GPU tiêu dùng và GPU máy chủ (cụ thể ở đây là RTX 2080 so với Tesla V100).
```

2020-10-14 03:23 UTC, cuongvng commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +hoặc thiếu dây đai phù hợp (như một trong những đồng tác giả đau đớn phát hiện ra).
```suggestion
hoặc thiếu dây nối phù hợp (như một trong các đồng tác giả đau đớn phát hiện ra).
```

2020-10-14 13:16 UTC, cuongvng requested changes
L41-L47 chưa dịch ạ @LongNguyen1984. Còn vài suggestions bị ẩn nữa ạ.

2020-10-14 13:29 UTC, duythanhvn commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +*dịch đoạn phía trên*
@LongNguyen1984 nhờ anh dịch giúp em đoạn này nữa anh nha. Em cảm ơn anh ạ.

2020-10-15 12:27 UTC, LongNguyen1984 commented on chapter_appendix-tools-for-deep-learning/selecting-servers-gpus_vn.md
> +*dịch đoạn phía trên*
Đã bổ sung

2020-10-15 12:30 UTC, cuongvng approved these changes

2020-10-15 15:30 UTC, merged